Update build script.
Allow add_to_tar to gather files from build directory of 3rdparty packages.
Rename build_android.sh to dobuild

diff --git a/dobuild b/dobuild
--- a/dobuild
+++ b/dobuild
@@ -1,4 +1,176 @@
-mkdir build
-cd build
-cmake ..
-make install
+#!/bin/sh
+set -euo pipefail
+shopt -s failglob
+
+# 'Debug', 'Release' or empty string for both
+BUILD_TYPE=
+
+THIS_FILE=$(readlink -f "$0")
+BASEDIR=$(dirname "$THIS_FILE")
+
+ANDROID_3RDPARTY_DIR=$BASEDIR/android-3rdparty
+ANDROID_LIB_DIR=$BASEDIR/android-libpdf2htmlex
+ANDROID_APP_DIR=$BASEDIR/android-sample-app
+
+# This is the .externalNativeBuild
+BUILD_3RDPARTY_DIR=$BASEDIR/build/3rdparty
+BUILD_LIB_DIR=$BASEDIR/build/libpdf2htmlex
+
+GRADLE_BUILD_3RDPARTY_DIR=$BASEDIR/build/gradle_3rdparty
+
+# Use android-libpdf2htmlex as a template for android-3rdparty Android Gradle project
+if ! test -d $ANDROID_3RDPARTY_DIR
+then
+  mkdir $ANDROID_3RDPARTY_DIR --verbose
+  cp --recursive $ANDROID_LIB_DIR/app $ANDROID_3RDPARTY_DIR/app
+
+  # Prepare build.gradle
+  sed -i "s/path \"..\/..\/CMakeLists.txt\"/path \"..\/..\/3rdparty\/CMakeLists.txt\"/g" $ANDROID_3RDPARTY_DIR/app/build.gradle
+
+  sed -i "s/buildStagingDirectory \"..\/..\/build\/libpdf2htmlex\/\"/buildStagingDirectory \"${BUILD_3RDPARTY_DIR//\//\\\/}\/\"/g" $ANDROID_3RDPARTY_DIR/app/build.gradle
+
+  # gradle.properties defines buildDir
+  grep -v 'buildDir=' $ANDROID_LIB_DIR/gradle.properties > $ANDROID_3RDPARTY_DIR/gradle.properties
+  echo "buildDir=$GRADLE_BUILD_3RDPARTY_DIR" >> $ANDROID_3RDPARTY_DIR/gradle.properties
+fi
+
+to_symlink="gradle build.gradle gradlew settings.gradle"
+for f in $to_symlink
+do
+  if ! test -e $ANDROID_3RDPARTY_DIR/$f
+  then
+    ln --symbolic $ANDROID_LIB_DIR/$f $ANDROID_3RDPARTY_DIR/$f --verbose
+  fi
+done
+
+# Build 3rdparty libraries
+cd $ANDROID_3RDPARTY_DIR
+./gradlew assemble$BUILD_TYPE
+
+pids=
+for build_target in $BUILD_3RDPARTY_DIR/cmake/*/*
+do
+  cmake --build $build_target &
+  pids="$pids $!"
+done
+
+for pid in $pids
+do
+  if ! wait $pid
+  then
+    echo "Build failed. Waiting for other subprocesses..."
+    wait
+    exit 1
+  fi
+done
+
+# Build libpdf2htmlEX
+cd $ANDROID_LIB_DIR
+./gradlew assemble$BUILD_TYPE
+
+for build_target in $BUILD_LIB_DIR/cmake/*/*
+do
+  cmake --build $build_target --target install
+
+  abi=$(basename $build_target)
+  build_type=$(basename ${build_target%$abi})
+
+  # ######
+  # UPX disabled because it fails for shared libraries...
+  # ######
+  # UPX only works on armeabi-v7a
+  # Other ABIs produce segfaults.
+  # Also no point in compressing debug builds.
+  #if test $abi = "armeabi-v7a" && test "$build_type" != "debug"
+  #then
+  #  upx --ultra-brute $build_target/built/lib/libpdf2htmlEX.so
+  #fi
+done
+
+# Rename .cmake.in to .cmake and pack it into .tar
+tar --create --file $BASEDIR/build/pdf2htmlEX-release.tar --directory=$BASEDIR pdf2htmlEX.cmake.in --transform 's,^pdf2htmlEX.cmake.in$,jniLibs/pdf2htmlEX.cmake,'
+tar --create --file $BASEDIR/build/pdf2htmlEX-debug.tar --directory=$BASEDIR pdf2htmlEX.cmake.in --transform 's,^pdf2htmlEX.cmake.in$,jniLibs/pdf2htmlEX.cmake,'
+
+function add_to_tar() {
+  for build_type in "Debug" "Release"
+  do
+    # deCapitalize Release -> release
+    local build_type_lowercase=${build_type,}
+    local tar_file=${BASEDIR}/build/pdf2htmlEX-${build_type_lowercase}.tar
+
+    if test ${src_type:-"installed"} = "installed"
+    then
+      local build_target_location=$BUILD_3RDPARTY_DIR/$build_type
+    else
+      local build_target_location=$BUILD_3RDPARTY_DIR/cmake/$build_type_lowercase
+      local src_dir=${package}-prefix/src/$package/$src_dir
+    fi
+
+    if test ! -d $build_target_location
+    then
+      continue
+    fi
+
+    for build_target in $(find $build_target_location -mindepth 1 -maxdepth 1)
+    do
+      local abi=$(basename $build_target)
+      local target_dir_=${target_dir/\-ABI\-/$abi}
+
+      tar --append --file $tar_file --directory=$build_target/$src_dir $filter --transform "s,^,$target_dir_/,"
+
+      if ${same_for_all_abis:-false}
+      then
+        for f in $filter
+        do
+          diff --brief --from-file "$build_target_location/*/$src_dir/$f"
+        done
+        break
+      fi
+    done
+  done
+}
+
+(
+  src_dir="lib"
+  filter="libpdf2htmlEX.so"
+  target_dir="jniLibs/-ABI-"
+  add_to_tar
+)
+
+(
+  src_dir="include"
+  filter="pdf2htmlEX"
+  target_dir="jniLibs/include"
+  same_for_all_abis=true
+  add_to_tar
+)
+
+(
+  src_dir="share"
+  filter="pdf2htmlEX"
+  target_dir="assets"
+  same_for_all_abis=true
+  add_to_tar
+)
+
+(
+  src_dir="share"
+  filter="poppler"
+  target_dir="assets"
+  same_for_all_abis=true
+  add_to_tar
+)
+
+# Load libpdf2htmlEX into sample android app
+tar_to_load=$BASEDIR/build/pdf2htmlEX-release.tar
+if test "$BUILD_TYPE" = "Debug"
+then
+  tar_to_load=$BASEDIR/build/pdf2htmlEX-debug.tar
+fi
+
+tar --extract --file $tar_to_load --directory=$ANDROID_APP_DIR/app/src/main jniLibs assets
+
+# Build sample android app
+cd $ANDROID_APP_DIR
+./gradlew assemble$BUILD_TYPE
+
